<?php

/**
 * Implementation of hook_init().
 */
function mysite_init() {
  // The path to the mysite module.
  $path = drupal_get_path('module', 'mysite');
  drupal_add_css($path . '/mysite.css');
}

/**
 * Implementation of hook_form_alter().
 */
function mysite_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  // Alter comment form for anonymous users.
  if ($user->uid == 0 && $form_id == 'comment_form') {
    // Use the Devel module to analyze the form array.
    // dpm($form);

    $form['name']['#prefix'] = '<div class="comment-contact">';


    $form['homepage']['#suffix'] = '</div>';

    // Get the path to the mysite module.
    $path = drupal_get_path('module', 'mysite');
    drupal_add_css($path . '/mysite.css');
  }
}

