<?php

/**
 * Implementation of hook_form_alter().
 */
function mysite_form_alter(&$form, &$form_state, $form_id) {
//  dpm($form_id);
//  dpm($form);

  if (isset($form['#node']) && $form['#node']->type .'_node_form' == $form_id) {
    // Move categories and menu fieldset below the body
    // field. We are assuming here that the taxonomy and menu
    // modules are enabled.
    $form['taxonomy']['#weight'] = 2;
    $form['menu']['#weight'] = 3;
  }
}

