<?php

/**
 * Implementation of hook_init().
 */
function mysite_init() {
  // The path to the mysite module.
  $path = drupal_get_path('module', 'mysite');
  drupal_add_js($path . '/js/search.js');
}

/**
 * Implementation of hook_form_alter().
 */
function mysite_form_alter(&$form, &$form_state, $form_id) {
  // Set the class attribute and add some JS goodness to the
  // search form when both the theme search box as well as
  // the basic search form are visible.
  if ($form_id == 'search_form') {
    // Set the class attribute of the search form textfield.
    $form['basic']['inline']['keys']['#attributes'] = array('class' => 'search-text');

    // The path to the mysite module.
    $path = drupal_get_path('module', 'mysite');
    drupal_add_js($path . '/js/search.js');
  }
  else if ($form_id == 'search_theme_form') {

    // Set the class attribute of the search-box textfield.
    $form['search_theme_form']['#attributes'] = array('class' => 'search-text');
  }
}

