<?php

/**
 * Implementation of hook_form_alter().
 */
function mysite_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node']) && $form['#node']->type .'_node_form' == $form_id) {
    $form['revision_information']['#postscript'] = t('If a new revision is to be created, please ensure that a log message is added detailing any changes.');
  }
}

/**
 * Add a custom attribute to the fieldset element.
 */
function phptemplate_fieldset($element) {
  if (!empty($element['#collapsible'])) {
    drupal_add_js('misc/collapse.js');

    if (!isset($element['#attributes']['class'])) {
      $element['#attributes']['class'] = '';
    }

    $element['#attributes']['class'] .= ' collapsible';
    if (!empty($element['#collapsed'])) {
      $element['#attributes']['class'] .= ' collapsed';
    }
  }

  return '<fieldset'. drupal_attributes($element['#attributes']) .'>'. ($element['#title'] ? '<legend>'. $element['#title'] .'</legend>' : '') . (isset($element['#description']) && $element['#description'] ? '<div class="description">'. $element['#description'] .'</div>' : '') . (!empty($element['#children']) ? $element['#children'] : '') . (isset($element['#value']) ? $element['#value'] : '') .  (isset($element['#postscript']) && $element['#postscript'] ? '<div class="postscript">'. $element['#postscript'] .'</div>' : '') ."</fieldset>\n";
}

